name: Build and Test PR

on:
  pull_request:
    branches:
    - main


jobs:
  build-windows:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.425
    - name: Setup .NET Core 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.400
    - name: Restore .NET local tools
      run: dotnet tool restore
    - name: Restore packages
      run: dotnet paket restore
    - name: Build and test (Release)
      env:
        FAKE_DETAILED_ERRORS: true
      run: dotnet run --project build/build.fsproj -- -t All
    - name: Build (Debug)
      run: dotnet build -c Debug -v n

  build-ubuntu:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.425
    - name: Setup .NET Core 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.400
    - name: Restore .NET local tools
      run: dotnet tool restore
    - name: Restore packages
      run: dotnet paket restore
    - name: Format code
      run: dotnet fake build -t Format
    - name: Build and test
      run: dotnet run --project build/build.fsproj -- -t RunTests
    - name: Build (Debug)
      run: dotnet build -c Debug -v n
